-- CREATE TABLE profiles (
--     id VARCHAR(255) NOT NULL,
--     name VARCHAR(255) NOT NULL,
--     email VARCHAR(255) NOT NULL,
--     picture VARCHAR(255) NOT NULL,
--     PRIMARY KEY (id)
-- )
-- CREATE TABLE items (
--     title VARCHAR(255) NOT NULL,
--     description VARCHAR(255) NOT NULL,
--     price DECIMAL NOT NULL,
--     salePrice DECIMAL,
--     picture VARCHAR(255) NOT NULL,
--     quantity INT NOT NULL,
--     id INT NOT NULL AUTO_INCREMENT,
--     rating INT NOT NULL,
--     isAvailable TINYINT NOT NULL,
--     creatorId VARCHAR(255) NOT NULL,
--     PRIMARY KEY (id),
--         FOREIGN KEY (creatorId)
--         REFERENCES profiles(id)
--         ON DELETE CASCADE
-- )

